### ISSUE TITLE
didSelectDate returning incorrect days

### ISSUE THREAD

**Issue by ghost** [nbwar/NWCalendarView#5]
Dowloaded and ran the demo in the master today, and found that on selecting a date, ViewController.swift line 52:

> print("Selected date (fromDate.date!) to date (toDate.date!)")

returned incorrect dates. For example, with default settings: clicking Nov 15 would select Nov 15 - Nov 21 on the calendar (coloured red), but the console returns:

> Selected date 2015-11-14 17:00:00 +0000 to date 2015-11-20 17:00:00 +0000

(GMT +7, I live in Bangkok).
Found that NWCalendarMonthContentView.swift line 393, changing:

> day.day -= 1

into:

> dayView.day!.day += 1 // day.day -= 1

solves this issue. It now returns the correct selected dates:

> Selected date 2015-11-15 17:00:00 +0000 to date 2015-11-21 17:00:00 +0000

However, on line 403 (after if notifyDelegate{}) I added:

> dayView.day!.day -= 1

to prevent selection issues on the calendar.

**Comment by nbwar** [comment]
The problem is when `NSDateComponents` is converted to date defaults to local timezone. Your fix dangerously modifies the `dayView.day` which is why you have to `-= 1` on line 403. It also only fixes the issue for your timezone and recreates the bug for other timezones.

I did submit a fix by hardcoding `dayView.day` timezone to UTC so that date will not be converted to timezone

see https://github.com/nbwar/NWCalendarView/commit/905c09eb7497a5fa3359d52725302595008c3470

**Comment by nbwar** [comment]
The problem is when `NSDateComponents` converts to `NSDate` it uses local timezone. I fixed it by settings the overall `NSCalendar` to UTC so conversion won't happen. 

see https://github.com/nbwar/NWCalendarView/commit/ad6651ba7ac84c706ee77f12442c0b2d8633ac0e

Thanks for reporting. If you have anymore issues let me know.

**Comment by ghost** [comment]
Awesome, seems to be fixed now. Thanks for the swift response.
